/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "tertiary": "#00632b",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003cad",
        "on-error-container": "#93000a",
        "primary-container": "#0f5fff",
        "surface-container-highest": "#d9e3f6",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#00201c",
        "secondary-container": "#73f8e6",
        "tertiary-fixed-dim": "#57e07d",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#52dbca",
        "surface-variant": "#d9e3f6",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#c8ffcc",
        "background": "#f8f9ff",
        "primary": "#0049cd",
        "on-surface": "#121c2a",
        "error": "#ba1a1a",
        "surface-container": "#e6eeff",
        "surface-dim": "#d0dbed",
        "on-secondary-fixed-variant": "#005048",
        "tertiary-container": "#007f39",
        "on-surface-variant": "#424656",
        "on-background": "#121c2a",
        "outline-variant": "#c3c5d9",
        "on-tertiary-fixed-variant": "#005323",
        "surface-tint": "#0051e1",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#73f8e6",
        "tertiary-fixed": "#75fd97",
        "primary-fixed": "#dce1ff",
        "surface-container-high": "#dee9fc",
        "outline": "#737687",
        "inverse-primary": "#b5c4ff",
        "on-secondary-container": "#007167",
        "on-secondary": "#ffffff",
        "on-primary-container": "#f0f0ff",
        "secondary": "#006a60",
        "on-tertiary-fixed": "#00210a",
        "inverse-on-surface": "#eaf1ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00164d",
        "inverse-surface": "#27313f",
        "primary-fixed-dim": "#b5c4ff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        md: "16px",
        "margin-tablet": "32px",
        gutter: "16px",
        "margin-mobile": "16px",
        xs: "4px",
        "touch-target": "44px",
        sm: "8px",
        xl: "32px",
        lg: "24px",
        base: "8px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Atkinson Hyperlegible Next"],
        "body-lg": ["Atkinson Hyperlegible Next"],
        "label-sm": ["Atkinson Hyperlegible Next"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "title-lg": ["Atkinson Hyperlegible Next"],
        "label-lg": ["Atkinson Hyperlegible Next"]
      }
    }
  },
  plugins: [],
}
