import { FormEvent, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { authenticateWithEGovAccessToken } from '../services/eGovAuthService'

const EGovSignInForm = () => {
  const navigate = useNavigate()
  const { login } = useAuth()
  const [email, setEmail] = useState('josie@yopmail.com')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (isSubmitting) return

    setError(null)
    setIsSubmitting(true)

    try {
      const user = await authenticateWithEGovAccessToken(email, password)
      login(user)
      setPassword('')
      navigate('/home', { replace: true })
    } catch (signInError) {
      setError(signInError instanceof Error ? signInError.message : 'Unable to sign in with eGovPH.')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <form
      onSubmit={handleSubmit}
      className="w-full rounded-2xl border border-outline-variant/40 bg-white/90 p-5 text-left shadow-lg space-y-4"
    >
      <div>
        <h3 className="font-bold text-on-surface text-lg">Sign in to eBuddy</h3>
        <p className="text-xs text-on-surface-variant mt-1 leading-relaxed">
          Use the email from your eGovPH profile. For this prototype, paste the SSO exchange code generated by the test portal or a valid SSO access token as your password.
        </p>
      </div>

      <label className="block space-y-1.5">
        <span className="text-xs font-bold text-on-surface">Email address</span>
        <div className="relative">
          <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-lg">
            mail
          </span>
          <input
            type="email"
            value={email}
            onChange={event => setEmail(event.target.value)}
            autoComplete="username"
            required
            disabled={isSubmitting}
            className="w-full h-12 rounded-xl border border-outline-variant bg-white pl-10 pr-3 text-sm text-on-surface outline-none focus:border-primary focus:ring-2 focus:ring-primary/15 disabled:opacity-60"
            placeholder="Email returned by the eGovPH API"
          />
        </div>
      </label>

      <label className="block space-y-1.5">
        <span className="text-xs font-bold text-on-surface">Password</span>
        <div className="relative">
          <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-lg">
            key
          </span>
          <input
            type={showPassword ? 'text' : 'password'}
            value={password}
            onChange={event => setPassword(event.target.value)}
            autoComplete="current-password"
            required
            disabled={isSubmitting}
            spellCheck={false}
            className="w-full h-12 rounded-xl border border-outline-variant bg-white pl-10 pr-12 text-sm text-on-surface outline-none focus:border-primary focus:ring-2 focus:ring-primary/15 disabled:opacity-60 font-mono"
            placeholder="Paste SSO exchange code or access token"
          />
          <button
            type="button"
            onClick={() => setShowPassword(value => !value)}
            disabled={isSubmitting}
            className="absolute right-2 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full text-on-surface-variant hover:bg-surface-container flex items-center justify-center disabled:opacity-50"
            aria-label={showPassword ? 'Hide access token' : 'Show access token'}
          >
            <span className="material-symbols-outlined text-lg">
              {showPassword ? 'visibility_off' : 'visibility'}
            </span>
          </button>
        </div>
        <span className="block text-[10px] text-on-surface-variant">
          The credential is used only for eGovPH authentication and is not saved in local storage. Do not use an AI Integration API token here.
        </span>
      </label>

      {error && (
        <div className="rounded-xl border border-error/25 bg-error-container/40 px-3 py-2.5 flex items-start gap-2 text-on-error-container">
          <span className="material-symbols-outlined text-lg shrink-0">error</span>
          <p className="text-xs font-medium leading-relaxed">{error}</p>
        </div>
      )}

      <button
        type="submit"
        disabled={isSubmitting || !email.trim() || !password.trim()}
        className="w-full h-12 bg-primary text-white font-bold rounded-full shadow-lg active:scale-[0.98] transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        <span
          className={`material-symbols-outlined ${isSubmitting ? 'animate-spin' : ''}`}
          style={{ fontVariationSettings: "'FILL' 1" }}
        >
          {isSubmitting ? 'progress_activity' : 'login'}
        </span>
        {isSubmitting ? 'Verifying with eGovPH...' : 'Sign in'}
      </button>
    </form>
  )
}

export default EGovSignInForm
